import 'package:flutter/material.dart';

void main() {
  runApp(const start_screen());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class start_screen extends StatelessWidget {
  const start_screen({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          StartPage(),
        ]),
      ),
    );
  }
}

class StartPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 360,
                  height: 153,
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Image.asset("assets/images/top_bar_wave/wave.png"),
                      Image.asset("assets/images/top_bar_wave/wave_shadow.png"),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 786,
                child: Container(
                  width: 360,
                  height: 14,
                  decoration: BoxDecoration(color: Color(0xFF72AAD8)),
                ),
              ),
              Positioned(
                left: 80,
                top: 279,
                child: Container(
                  width: 200,
                  height: 200,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 200,
                          height: 200,
                          decoration: ShapeDecoration(
                            color: Color(0xFFE6F4FE),
                            shape: OvalBorder(
                              side: BorderSide(width: 1, color: Colors.white),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 200,
                          height: 200,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image:
                                  AssetImage("assets/images/logo/gaorre.png"),
                              fit: BoxFit.cover,
                            ),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              const Positioned(
                left: 57,
                top: 199,
                child: Stack(
                  children: [
                    Positioned(
                      left: 0,
                      top: 293,
                      child: Text(
                        '원격 줄서기 원격 주문 서비스',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Color(0xFF72AAD8),
                          fontSize: 24,
                          fontFamily: 'Dovemayo_gothic',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                    Positioned(
                      left: 27,
                      top: 0,
                      child: Text(
                        '가 오 리',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Color(0xFF72AAD8),
                          fontSize: 64,
                          fontFamily: 'Dovemayo_gothic',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 20,
                top: 568,
                child: Container(
                  width: 320,
                  height: 48,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 320,
                          height: 48,
                          decoration: ShapeDecoration(
                            color: Color(0xFF72AAD8),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(15),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        right: 0,
                        bottom: 0,
                        child: ElevatedButton(
                          onPressed: () {
                            // 버튼이 클릭되었을 때 실행될 작업을 여기에 추가하세요
                          },
                          style: ElevatedButton.styleFrom(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(15),
                            ),
                            backgroundColor: Colors.transparent,
                            elevation: 0,
                          ),
                          child: Text(
                            '로그인',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 24,
                              fontFamily: 'Dovemayo_gothic',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
